services:
  distributedcaching:
    image: ${DOCKER_REGISTRY-}distributedcaching
    container_name: distributedcaching
    build:
      context: .
      dockerfile: DistributedCaching/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
  database.caching:
    image: postgres:latest
    container_name: database.caching
    environment:
        - POSTGRES_DB={YOUR_DB}
        - POSTGRES_USER={YOUR_USER}
        - POSTGRES_PASSWORD={YOUR_PASS}
    volumes:
        - db-cache:/var/lib/postgresql/data
    ports:
        - 5432:5432
  redis.caching:
    image: redis:latest
    restart: always
    ports:
        - '6379:6379' 
volumes:
  db-cache: 
